// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcMGpr6w4dbnz1TOaPHWMHx7uYEJ0MlWA',
    appId: '1:1077831778465:web:f14696c8b3918e1db9b0e0',
    messagingSenderId: '1077831778465',
    projectId: 'sendex-app-project',
    authDomain: 'sendex-app-project.firebaseapp.com',
    storageBucket: 'sendex-app-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZE21h1Ajp7h8rvDSt_Jo6bypW6xJSA_4',
    appId: '1:1077831778465:android:524805e5350ebfefb9b0e0',
    messagingSenderId: '1077831778465',
    projectId: 'sendex-app-project',
    storageBucket: 'sendex-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw_vfNPt9uSKzMQRNawcQ62pD1j6B5euM',
    appId: '1:1077831778465:ios:f2f14c9f445bfe33b9b0e0',
    messagingSenderId: '1077831778465',
    projectId: 'sendex-app-project',
    storageBucket: 'sendex-app-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw_vfNPt9uSKzMQRNawcQ62pD1j6B5euM',
    appId: '1:1077831778465:ios:f2f14c9f445bfe33b9b0e0',
    messagingSenderId: '1077831778465',
    projectId: 'sendex-app-project',
    storageBucket: 'sendex-app-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcMGpr6w4dbnz1TOaPHWMHx7uYEJ0MlWA',
    appId: '1:1077831778465:web:32535f16155b4efeb9b0e0',
    messagingSenderId: '1077831778465',
    projectId: 'sendex-app-project',
    authDomain: 'sendex-app-project.firebaseapp.com',
    storageBucket: 'sendex-app-project.firebasestorage.app',
  );
}
